### ISSUE TITLE
[Feature] Add recovery_window_in_days variable and pass arg to aws_secretsmanager_secret resource

### ISSUE THREAD

**Issue by askaribragimov** [rhythmictech/terraform-aws-secretsmanager-random-secret#9]
**Is your feature request related to a problem? Please describe.**
Re-creating stack with this module meets a problem of secrets being flagged for deletion but not deleted, if same name is used.  Terraform fails with an error. Manual cleanup of secrets is required.

**Describe the solution you'd like**
Pass parameter https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret#recovery_window_in_days
to the `aws_secretsmanager_secret` block of the module. This allows setting it to 0 and therefore avoiding the problem

**Comment by sblack4** [comment]
This should be easy; an extra variable and a line in this resource: 

https://github.com/rhythmictech/terraform-aws-secretsmanager-random-secret/blob/master/main.tf#L25

**Comment by JohnShortland** [comment]
@askaribragimov Pull request submitted with feature you requested

**Comment by sblack4** [comment]
This has been implemented in [v1.3.0](https://github.com/rhythmictech/terraform-aws-secretsmanager-random-secret/releases/tag/v1.3.0)
